### ISSUE TITLE
"Show deposit address" error

### ISSUE THREAD

**Issue by zed-wong** [awesome-mixin-network/bitcoin-cli-wallet-python#6]
python3 Bitcoin_wallet_mixin_consoleGUI.py
-load wallet 
-select wallet 
-balance
-choose any type of cryptocurrency
-Show deposit address 

An error occurred:
TypeError: can only concatenate str (not "NoneType") to str

![2 2020-04-24 19-45-12](https://user-images.githubusercontent.com/36271125/80209278-550d2d80-8664-11ea-9bce-fb4ce6d8a9d6.png)
![error 2020-04-24 19-45-40](https://user-images.githubusercontent.com/36271125/80209289-59394b00-8664-11ea-85c6-cb681331f3d4.png)

system:Ubuntu 20.04
python 3.8.2

**Comment by myrual** [comment]
I am not maintaining the code now. Please print log to found what happen
